volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  div_tz_yii:

services:
  php:
    build: ./docker/php
    container_name: php
    volumes_from:
      - source
    links:
      - db
      - memcached
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    networks:
      - div_tz_yii
    restart: unless-stopped
  web_server:
    build: ./docker/nginx
    container_name: web_server
    depends_on:
      - source
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:80:80'
      - '${INTERFACE}:443:443'
    links:
      - php
    networks:
      - div_tz_yii
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    restart: unless-stopped
  db:
    build: ./docker/mysql
    container_name: db
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Europe/Moscow
    command: mysqld --user=root --sql-mode=""
    networks:
      - div_tz_yii
    stdin_open: true
    tty: true
    restart: unless-stopped
  memcached:
    image: memcached:latest
    container_name: memcached
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:11211:11211'
    networks:
      - div_tz_yii
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    restart: unless-stopped
  adminer:
    image: dockette/adminer:full
    container_name: adminer
    links:
      - db:db
    ports:
      - '${INTERFACE}:8080:80'
    environment:
      UPLOAD: 1024M # upload_max_filesize, post_max_size
      TZ: Europe/Moscow
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - div_tz_yii
  source:
    image: alpine:latest
    container_name: source
    volumes:
      - ./docker/log/nginx:/var/log/nginx
      - ./docker/log/php:/var/log/php
      - ./docker/log/db:/var/log/mysql
      - ./docker/log/memcached:/var/log/memcached
      - db:/var/lib/mysql
      - cache:/var/lib/memcached
      - ./:/var/www/
      - /etc/localtime:/etc/localtime/:ro
    networks:
      - div_tz_yii
